#define R_BRACE	"{"
#define L_BRACE	"}"

#define FORWARD "FD"
#define R_TURN "RT"
#define L_TURN "LT"

#define SET "SET"
#define DO "DO"
#define FROM "FROM"
#define TO "TO"

#define ZERO 	"0"

#define P_EQUALS	":="
#define ADD 	"+"
#define SUB		"-"
#define MULT	"*"
#define DIV		"/"
#define END_POLISH	";"

#define IF	"IF"
#define ELIF	"ELIF"
#define ELSE	"ELSE"
#define G_THAN	">"
#define L_THAN	"<"
#define G_THAN_E	">="
#define L_THAN_E	"<="
#define	EQ	"=="
#define N_EQ	"!="
